=== manuelandreaskuhn/bsi-interfacedesign-tr03151/templates/bsi-tr-03153-03151/interfacedesign/_schema/functions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://www.bsi.bund.de/tr03151" 
           xmlns:tr="http://www.bsi.bund.de/tr03151"
           elementFormDefault="qualified">

  <!-- ============================= -->
  <!-- Imported/Referenced Types     -->
  <!-- ============================= -->
  
  <xs:import namespace="http://www.w3.org/2001/XMLSchema" schemaLocation="http://www.w3.org/2001/XMLSchema.xsd"/>

  <!-- ============================= -->
  <!-- Simple String Types           -->
  <!-- ============================= -->

  <xs:simpleType name="FunctionName">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="256"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Category">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- ============================= -->
  <!-- Detailed Steps Structure      -->
  <!-- ============================= -->

  <!-- ErrorCase: Error condition and exception -->
  <xs:complexType name="ErrorCase">
    <xs:sequence>
      <xs:element name="exception" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="trigger" type="xs:string" minOccurs="1"/>
      <xs:element name="action" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- SuccessCase: Success condition and action -->
  <xs:complexType name="SuccessCase">
    <xs:sequence>
      <xs:element name="condition" type="xs:string" minOccurs="1"/>
      <xs:element name="action" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- DetailedStep: Single step in function execution -->
  <xs:complexType name="DetailedStep">
    <xs:sequence>
      <xs:element name="number" type="xs:integer" minOccurs="1"/>
      <xs:element name="originalText" type="xs:string" minOccurs="0"/>
      <xs:element name="germanText" type="xs:string" minOccurs="1"/>
      <xs:element name="pseudocode" type="xs:string" minOccurs="0"/>
      <xs:element name="errorCase" type="tr:ErrorCase" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="successCase" type="tr:SuccessCase" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- DetailedSteps: Collection of steps -->
  <xs:complexType name="DetailedSteps">
    <xs:sequence>
      <xs:element name="step" type="tr:DetailedStep" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- ============================= -->
  <!-- Parameters Structure          -->
  <!-- ============================= -->

  <!-- Parameter: Function parameter definition -->
  <xs:complexType name="Parameter">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="1"/>
      <xs:element name="type" type="xs:string" minOccurs="1"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="direction" type="xs:string" minOccurs="0"/>
      <xs:element name="required" type="xs:boolean" minOccurs="0"/>
      <xs:element name="defaultValue" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Parameters: Collection of parameters -->
  <xs:complexType name="Parameters">
    <xs:sequence>
      <xs:element name="parameter" type="tr:Parameter" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- ============================= -->
  <!-- Return Value Structure        -->
  <!-- ============================= -->

  <!-- ReturnValue: Function return type -->
  <xs:complexType name="ReturnValue">
    <xs:sequence>
      <xs:element name="type" type="xs:string" minOccurs="1"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- ============================= -->
  <!-- Exceptions Structure          -->
  <!-- ============================= -->

  <!-- Exceptions: List of possible exceptions -->
  <xs:complexType name="Exceptions">
    <xs:sequence>
      <xs:element name="exception" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- ============================= -->
  <!-- Roles Structure               -->
  <!-- ============================= -->

  <!-- Roles: Authorized roles for function execution -->
  <xs:complexType name="Roles">
    <xs:sequence>
      <xs:element name="role" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- ============================= -->
  <!-- Requirement & Note Types      -->
  <!-- ============================= -->

  <!-- Requirement: Implementation requirement -->
  <xs:complexType name="Requirement">
    <xs:sequence>
      <xs:element name="level" type="xs:string" minOccurs="0"/>
      <xs:element name="description" type="xs:string" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Requirements: Collection of requirements -->
  <xs:complexType name="Requirements">
    <xs:sequence>
      <xs:element name="requirement" type="tr:Requirement" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Note: Additional note or comment -->
  <xs:complexType name="Note">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="type" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- ============================= -->
  <!-- Main Function Type            -->
  <!-- ============================= -->

  <!-- Function: Main function definition -->
  <xs:complexType name="Function">
    <xs:sequence>
      <xs:element name="name" type="tr:FunctionName" minOccurs="1"/>
      <xs:element name="category" type="tr:Category" minOccurs="1"/>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="authorizedRoles" type="tr:Roles" minOccurs="0"/>
      <xs:element name="detailedSteps" type="tr:DetailedSteps" minOccurs="0"/>
      <xs:element name="parameters" type="tr:Parameters" minOccurs="0"/>
      <xs:element name="returnValue" type="tr:ReturnValue" minOccurs="0"/>
      <xs:element name="exceptions" type="tr:Exceptions" minOccurs="0"/>
      <xs:element name="requirements" type="tr:Requirements" minOccurs="0"/>
      <xs:element name="note" type="tr:Note" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="precondition" type="xs:string" minOccurs="0"/>
      <xs:element name="postcondition" type="xs:string" minOccurs="0"/>
      <xs:element name="systemLog" type="xs:anyType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- ============================= -->
  <!-- Root Element                  -->
  <!-- ============================= -->

  <!-- Root element for function documents -->
  <xs:element name="function" type="tr:Function"/>

  <!-- Root element for collections of functions -->
  <xs:element name="functions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="function" type="tr:Function" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== manuelandreaskuhn/bsi-interfacedesign-tr03151/templates/bsi-tr-03153-03151/interfacedesign/functions/getDescription.xml
<?xml version='1.0' encoding='utf-8'?>
<function id="getDescription" xmlns="http://bsi.bund.de/TR03151" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bsi.bund.de/TR03151 ../../schema/functions.xsd">
  <name>getDescription</name>
  <category>Geräteinitialisierung</category>
  <description>The function getDescription can be used to obtain the short description of the device that is set using the function setDescription and also provided in the in the device information file.</description>
  <detailedSteps>
    <step>
      <number>1</number>
      <originalText>If the referencing guideline limits the access to the functionality solely to authenticated users, the function SHALL check if the user that has invoked the function has the status authenticated. If the status is not authenticated, the function SHALL raise the exception ErrorUserNotAuthenticated and exit the function.</originalText>
      <germanText>Prüft, ob Nutzer authentifiziert. Falls nicht: Exception ErrorUserNotAuthenticated, Ende.</germanText>
      <pseudocode>WENN Benutzer NICHT authentifiziert DANN
  WERFE ErrorUserNotAuthenticated
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorUserNotAuthenticated</exception>
        <trigger>Der Benutzer ist nicht authentifiziert</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>2</number>
      <originalText>If the referencing guideline limits the access to the functionality to certain roles, the function SHALL check in the corresponding role if the (unauthenticated) user is authorized to execute the function. If the user is not authorized, the function SHALL raise the exception ErrorUserNotAuthorized and exit the function.</originalText>
      <germanText>Prüft, ob Nutzer berechtigt. Falls nicht: Exception ErrorUserNotAuthorized, Ende.</germanText>
      <pseudocode>WENN Benutzer NICHT autorisiert DANN
  WERFE ErrorUserNotAuthorized
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorUserNotAuthorized</exception>
        <trigger>Der Benutzer ist nicht berechtigt</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>3</number>
      <originalText>The function SHALL determine information needed to populate the variable $6 as defined in chapter 2.5.3. A not set description SHALL be represented by an empty string. If the determination of the description fails, the function SHALL raise the exception ErrorGetDescriptionFailed and exit the function.</originalText>
      <germanText>Ermittelt Beschreibung. Bei Fehler: Exception ErrorGetDescriptionFailed, Ende.</germanText>
      <pseudocode>VERSUCHE
  ERMITTLE Beschreibungsinformation
BEI_FEHLER
  WERFE ErrorGetDescriptionFailed
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorGetDescriptionFailed</exception>
        <trigger>Die Ermittlung der Beschreibung schlägt fehl</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>4</number>
      <originalText>If the determination of all information needed to populate the variable $6 as defined in chapter 2.5.3 is successful, the function SHALL return this information using the output parameter description. Additionally, the function SHALL return without raising an exception to indicate that the execution of the function has been successful.</originalText>
      <germanText>Gibt Beschreibung zurück. Bei Erfolg keine Exception.</germanText>
      <pseudocode>GEBE Beschreibung zurück (description Parameter)
RETURN ohne Exception</pseudocode>
      <successCase>
        <condition>Ausführung war erfolgreich</condition>
        <action>Funktion kehrt ohne Exception zurück</action>
      </successCase>
    </step>
  </detailedSteps>
  <parameters />
  <returnValue>
    <type>String</type>
    <description>a short description of the device.</description>
  </returnValue>
  <exceptions>
    <exception>ErrorDeviceNotInitialized</exception>
    <exception>ErrorFunctionFailed</exception>
    <exception>ErrorFunctionNotSupported</exception>
    <exception>ErrorGetDescriptionFailed</exception>
    <exception>ErrorParameterSyntax</exception>
    <exception>ErrorStorageMediumDisconnected</exception>
    <exception>ErrorUserNotAuthenticated</exception>
    <exception>ErrorUserNotAuthorized</exception>
  </exceptions>
</function>

=== manuelandreaskuhn/bsi-interfacedesign-tr03151/templates/bsi-tr-03153-03151/interfacedesign/functions/exportLoggingCertificates.xml
<?xml version='1.0' encoding='utf-8'?>
<function id="exportLoggingCertificates" xmlns="http://bsi.bund.de/TR03151" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bsi.bund.de/TR03151 ../../schema/functions.xsd">
  <name>exportLoggingCertificates</name>
  <category>Logging</category>
  <description>The function exportLoggingCertificates exports the certificates of the certificate chains. These certificates belong to the public keys of the key pairs that are used for the creation of signature values in log messages stored on the device. This includes the higher level certificates that form the complete certificate chain.</description>
  <detailedSteps>
    <step>
      <number>1</number>
      <originalText>If the referencing guideline limits the access to the functionality solely to authenticated users, the function SHALL check if the user that has invoked the function has the status authenticated. If the status is not authenticated, the function SHALL raise the exception ErrorUserNotAuthenticated and exit the function.</originalText>
      <germanText>Prüft, ob Nutzer authentifiziert. Falls nicht: Exception ErrorUserNotAuthenticated, Ende.</germanText>
      <pseudocode>WENN Benutzer NICHT authentifiziert DANN
  WERFE ErrorUserNotAuthenticated
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorUserNotAuthenticated</exception>
        <trigger>Der Benutzer ist nicht authentifiziert</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>2</number>
      <originalText>If the referencing guideline limits the access to the functionality to certain roles, the function SHALL check in the corresponding role if the (unauthenticated) user is authorized to execute the function. If the user is not authorized, the function SHALL raise the exception ErrorUserNotAuthorized and exit the function.</originalText>
      <germanText>Prüft, ob Nutzer berechtigt. Falls nicht: Exception ErrorUserNotAuthorized, Ende.</germanText>
      <pseudocode>WENN Benutzer NICHT autorisiert DANN
  WERFE ErrorUserNotAuthorized
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorUserNotAuthorized</exception>
        <trigger>Der Benutzer ist nicht berechtigt</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>3</number>
      <originalText>This function SHALL collect the certificates of the certificate chains. These certificates belong to the key pairs that are used to create signature values contained in log messages. If the collection of the certificates fails, the function SHALL raise the exception ErrorExportLoggingCertificateFailed and exit the function.</originalText>
      <germanText>Sammelt Zertifikate. Bei Fehler: Exception ErrorExportLoggingCertificateFailed, Ende.</germanText>
      <pseudocode>VERSUCHE
  SAMMELE Zertifikate der Zertifikatsketten
BEI_FEHLER
  WERFE ErrorExportLoggingCertificateFailed
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorExportLoggingCertificateFailed</exception>
        <trigger>Die Erfassung der Zertifikate schlägt fehl</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>4</number>
      <originalText>The function SHALL return the collected certificates in a TAR archive by the output parameter certificates. The function SHALL return the file name for the TAR archive by fileName. Additionally, the function SHALL return without raising an exception to indicate that the execution of the function has been successful.</originalText>
      <germanText>Gibt Zertifikate als TAR-Archiv zurück. Bei Erfolg keine Exception.</germanText>
      <pseudocode>GEBE Zertifikate als TAR-Archiv zurück (certificates Parameter)
GEBE Dateinamen des TAR-Archivs zurück (fileName Parameter)
RETURN ohne Exception</pseudocode>
      <successCase>
        <condition>Ausführung war erfolgreich</condition>
        <action>Funktion kehrt ohne Exception zurück</action>
      </successCase>
    </step>
  </detailedSteps>
  <parameters />
  <returnValue>
    <type>ExportDataResult</type>
    <description>an ExportDataResult which contains an InputStream delivering a TAR archive with all certificates necessary for log message verification, and the filename of the TAR archive.</description>
  </returnValue>
  <exceptions>
    <exception>ErrorDeviceNotInitialized</exception>
    <exception>ErrorFunctionFailed</exception>
    <exception>ErrorExportLoggingCertificateFailed</exception>
    <exception>ErrorFunctionNotSupported</exception>
    <exception>ErrorParameterSyntax</exception>
    <exception>ErrorStorageMediumDisconnected</exception>
    <exception>ErrorUserNotAuthenticated</exception>
    <exception>ErrorUserNotAuthorized</exception>
  </exceptions>
</function>

=== manuelandreaskuhn/bsi-interfacedesign-tr03151/templates/bsi-tr-03153-03151/interfacedesign/functions/exportSerialNumbers.xml
<?xml version='1.0' encoding='utf-8'?>
<function id="exportSerialNumbers" xmlns="http://bsi.bund.de/TR03151" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bsi.bund.de/TR03151 ../../schema/functions.xsd">
  <name>exportSerialNumbers</name>
  <category>Logging</category>
  <description>Exports the serial number(s) of the SE API. A serial number is a hash value of a public key that belongs to a key pair whose private key was used to sign log messages.</description>
  <detailedSteps>
    <step>
      <number>1</number>
      <originalText>If the referencing guideline limits the access to the functionality solely to authenticated users, the function SHALL check if the user that has invoked the function has the status authenticated. If the status is not authenticated, the function SHALL raise the exception ErrorUserNotAuthenticated and exit the function.</originalText>
      <germanText>Prüft, ob Nutzer authentifiziert. Falls nicht: Exception ErrorUserNotAuthenticated, Ende.</germanText>
      <pseudocode>WENN Benutzer NICHT authentifiziert DANN
  WERFE ErrorUserNotAuthenticated
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorUserNotAuthenticated</exception>
        <trigger>Der Benutzer ist nicht authentifiziert</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>2</number>
      <originalText>If the referencing guideline limits the access to the functionality to certain roles, the function SHALL check in the corresponding role if the (unauthenticated) user is authorized to execute the function. If the user is not authorized, the function SHALL raise the exception ErrorUserNotAuthorized and exit the function.</originalText>
      <germanText>Prüft, ob Nutzer berechtigt. Falls nicht: Exception ErrorUserNotAuthorized, Ende.</germanText>
      <pseudocode>WENN Benutzer NICHT autorisiert DANN
  WERFE ErrorUserNotAuthorized
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorUserNotAuthorized</exception>
        <trigger>Der Benutzer ist nicht berechtigt</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>3</number>
      <originalText>The function exportSerialNumbers SHALL collect the serial number(s) of the device. If the collection of serial numbers fails, the function SHALL raise the exception ErrorExportSerialNumbersFailed and exit the function.</originalText>
      <germanText>Sammelt Seriennummer(n). Bei Fehler: Exception ErrorExportSerialNumbersFailed, Ende.</germanText>
      <pseudocode>VERSUCHE
  SAMMELE Seriennummern des Geräts
BEI_FEHLER
  WERFE ErrorExportSerialNumbersFailed
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorExportSerialNumbersFailed</exception>
        <trigger>Die Erfassung der Seriennummern schlägt fehl</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>4</number>
      <originalText>If the collection of the serial number(s) has been successful, the function SHALL return the determined serial number(s) over the output parameter serialNumbers. Additionally, the function SHALL return without raising an exception to indicate that the execution of the function has been successful.</originalText>
      <germanText>Gibt Seriennummer(n) zurück. Bei Erfolg keine Exception.</germanText>
      <pseudocode>GEBE Seriennummern zurück (serialNumbers Parameter)
RETURN ohne Exception</pseudocode>
      <successCase>
        <condition>Die Seriennummern wurden erfolgreich erfasst</condition>
        <action>Gibt Seriennummern zurück und kehrt ohne Exception zurück</action>
      </successCase>
    </step>
  </detailedSteps>
  <parameters />
  <returnValue>
    <type>byte[]</type>
    <description>the serial numbers of the public keys used by the Secure Element.</description>
  </returnValue>
  <exceptions>
    <exception>ErrorDeviceNotInitialized</exception>
    <exception>ErrorExportSerialNumbersFailed</exception>
    <exception>ErrorFunctionFailed</exception>
    <exception>ErrorFunctionNotSupported</exception>
    <exception>ErrorParameterSyntax</exception>
    <exception>ErrorStorageMediumDisconnected</exception>
    <exception>ErrorUserNotAuthenticated</exception>
    <exception>ErrorUserNotAuthorized</exception>
  </exceptions>
</function>

=== manuelandreaskuhn/bsi-interfacedesign-tr03151/templates/bsi-tr-03153-03151/interfacedesign/functions/getLastTransactionLogMessage.xml
<?xml version='1.0' encoding='utf-8'?>
<function id="getLastTransactionLogMessage" xmlns="http://bsi.bund.de/TR03151" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bsi.bund.de/TR03151 ../../schema/functions.xsd">
  <name>getLastTransactionLogMessage</name>
  <category>Client- und Transaktionsverwaltung</category>
  <description>This function returns the last transaction log message that has been produced and processed by the Secure Element filtered by a transaction number.</description>
  <detailedSteps>
    <step>
      <number>1</number>
      <originalText>If the referencing guideline limits the access to the functionality solely to authenticated users, the function SHALL check if the user that has invoked the function has the status authenticated. If the status is not authenticated, the function SHALL raise the exception ErrorUserNotAuthenticated and exit the function.</originalText>
      <germanText>Prüft, ob Nutzer authentifiziert. Falls nicht: Exception ErrorUserNotAuthenticated, Ende.</germanText>
      <pseudocode>WENN Benutzer NICHT authentifiziert DANN
  WERFE ErrorUserNotAuthenticated
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorUserNotAuthenticated</exception>
        <trigger>Der Benutzer ist nicht authentifiziert</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>2</number>
      <originalText>If the referencing guideline limits the access to the functionality to certain roles, the function SHALL check in the corresponding role if the (unauthenticated) user is authorized to execute the function. If the user is not authorized, the function SHALL raise the exception ErrorUserNotAuthorized and exit the function.</originalText>
      <germanText>Prüft, ob Nutzer berechtigt. Falls nicht: Exception ErrorUserNotAuthorized, Ende.</germanText>
      <pseudocode>WENN Benutzer NICHT autorisiert DANN
  WERFE ErrorUserNotAuthorized
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorUserNotAuthorized</exception>
        <trigger>Der Benutzer ist nicht berechtigt</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>3</number>
      <originalText>If the function is invoked with the parameter transactionNumber, the transaction log to be exported SHALL be the last transaction log created for the transaction number passed by the parameter. If no transaction log for the provided transaction number is found on the device, the exception ErrorNoLogMessageFound SHALL be raised and the function SHALL be exited.</originalText>
      <germanText>Mit Parameter transactionNumber: Ermittelt letztes Transaktionslog für diese Nummer. Falls nicht gefunden: Exception ErrorNoLogMessageFound, Ende.</germanText>
      <pseudocode>WENN Parameter transactionNumber vorhanden DANN
  SUCHE letztes Transaktionslog für diese Nummer
  WENN nicht gefunden DANN
    WERFE ErrorNoLogMessageFound
    BEENDE_FUNKTION
  ENDE
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorNoLogMessageFound</exception>
        <trigger>Kein Transaktionslog für die übergebene Nummer gefunden</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>4</number>
      <originalText>If the function is invoked without the parameter transactionNumber the transaction log to be exported SHALL be the most recent transaction log message created by the device. If no transaction log messages are found on the device, the exception ErrorNoLogMessageFound SHALL be raised and the function SHALL be exited.</originalText>
      <germanText>Ohne Parameter transactionNumber: Ermittelt aktuellstes Transaktionslog. Falls nicht gefunden: Exception ErrorNoLogMessageFound, Ende.</germanText>
      <pseudocode>WENN kein Parameter transactionNumber DANN
  SUCHE aktuellstes Transaktionslog
  WENN nicht gefunden DANN
    WERFE ErrorNoLogMessageFound
    BEENDE_FUNKTION
  ENDE
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorNoLogMessageFound</exception>
        <trigger>Kein Transaktionslog auf dem Gerät gefunden</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>5</number>
      <originalText>The function SHALL retrieve the transaction log message determined by the function. If the retrieval of the transaction log message fails, the exception ErrorReadingLogMessage SHALL be raised and the function SHALL be exited.</originalText>
      <germanText>Ruft das ermittelte Transaktionslog ab. Bei Fehler: Exception ErrorReadingLogMessage, Ende.</germanText>
      <pseudocode>VERSUCHE
  HOLE Transaktionslog
BEI_FEHLER
  WERFE ErrorReadingLogMessage
  BEENDE_FUNKTION
ENDE</pseudocode>
      <errorCase>
        <exception>ErrorReadingLogMessage</exception>
        <trigger>Der Abruf des Transaktionslogs schlägt fehl</trigger>
        <action>Funktion beenden</action>
      </errorCase>
    </step>
    <step>
      <number>6</number>
      <originalText>The retrieved transaction log message SHALL be returned to the application by the output parameter logMessageContent and logMessageFileName. The function SHALL return without raising an exception to indicate that the execution of the function has been successful.</originalText>
      <germanText>Gibt Transaktionslog und Dateiname zurück. Bei Erfolg keine Exception.</germanText>
      <pseudocode>GEBE Transaktionslog-Content zurück (logMessageContent Parameter)
GEBE Dateiname zurück (logMessageFileName Parameter)
RETURN ohne Exception</pseudocode>
      <successCase>
        <condition>Das Transaktionslog wurde erfolgreich abgerufen</condition>
        <action>Gibt das Transaktionslog-Content und den Dateinamen zurück und kehrt ohne Exception zurück</action>
      </successCase>
    </step>
  </detailedSteps>
  <parameters>
    <parameter>
      <name>transactionNumber</name>
      <type>long</type>
      <description>parameter is used to unambiguously identify the transaction.</description>
      <direction>INPUT</direction>
      <required>false</required>
      <note>This parameter is optional. The function has an overloaded version without parameters.</note>
    </parameter>
  </parameters>
  <returnValue>
    <type>ExportDataResult</type>
    <description>an ExportDataResult which contains an InputStream delivering the content of the last transaction log message and the filename of the log message.</description>
  </returnValue>
  <exceptions>
    <exception>ErrorDeviceNotInitialized</exception>
    <exception>ErrorFunctionFailed</exception>
    <exception>ErrorFunctionNotSupported</exception>
    <exception>ErrorNoLogMessageFound</exception>
    <exception>ErrorParameterSyntax</exception>
    <exception>ErrorReadingLogMessage</exception>
    <exception>ErrorSecureElementDisabled</exception>
    <exception>ErrorStorageMediumDisconnected</exception>
    <exception>ErrorUserNotAuthenticated</exception>
    <exception>ErrorUserNotAuthorized</exception>
  </exceptions>
</function>
